"""Add user_id to todos table AND CREATE users table

Revision ID: eaf9fd59c1ab
Revises: 65eb58cac041
Create Date: 2023-07-07 04:40:55.119015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaf9fd59c1ab'
down_revision = '65eb58cac041'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
